apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: prod

namePrefix: prod-

labels:
  - pairs:
      environment: prod

replicas:
  - name: web-app
    count: 5

patches:
  - target:
      kind: Database
      name: app-postgres
    patch: |-
      - op: replace
        path: /spec/storageSize
        value: "100Gi"
      - op: replace
        path: /spec/version
        value: "16.0"
  - target:
      kind: ConfigMap
      name: web-app-config
    patch: |-
      - op: replace
        path: /data/LOG_LEVEL
        value: "warn"
  - target:
      kind: Deployment
      name: web-app
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "200m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "256Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "1000m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "1Gi"
