apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: dev

namePrefix: dev-

labels:
  - pairs:
      environment: dev

replicas:
  - name: web-app
    count: 2

patches:
  - target:
      kind: Database
      name: app-postgres
    patch: |-
      - op: replace
        path: /spec/storageSize
        value: "10Gi"
  - target:
      kind: ConfigMap
      name: web-app-config
    patch: |-
      - op: replace
        path: /data/LOG_LEVEL
        value: "debug"
