apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - database-crd.yaml
  - database.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app: myapp
  managed-by: argocd
