apiVersion: v1
kind: ConfigMap
metadata:
  name: web-app-config
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "2"
data:
  DATABASE_HOST: app-postgres.default.svc.cluster.local
  DATABASE_PORT: "5432"
  DATABASE_NAME: appdb
  APP_PORT: "8080"
  LOG_LEVEL: info
