apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- database-crd.yaml
- database.yaml
- app-configmap.yaml
- app-secret.yaml
- app-deployment.yaml
- app-service.yaml

labels:
- pairs:
    app.kubernetes.io/name: web-app
    app.kubernetes.io/part-of: app-with-crds

namespace: default
